var debug = process.env.NODE_ENV !== "production";
var webpack = require('webpack');
if (debug) console.log("DEBUG MODE")

const outputFolder = debug ? "/bundles" : "/dist"

// This is the game line in the ChessState.js that makes it work
// exports.ChessState = ChessState_ChessState;
// TODO: figure out how this line above is generated by webpack

module.exports = {
  context: __dirname,
  devtool: 'inline-source-map',
  
  entry: "./lib/src/ChessState.js",
  module: {
     rules: [
     {
        test: /\.ts$/, 
        use: 'ts-loader',
        exclude: /node_modules/
     }
     ]
  },
  optimization: {
    minimize: !debug
  },
  resolve: {
     extensions: ['.ts', '.js']
  },
  output: {
    path: __dirname + outputFolder,
    filename: "ChessState.js"
  },
  plugins: debug ? [] : [
    new webpack.ProgressPlugin({
      handler: (percentage, message ) => {
        console.info(percentage, message);
      },
    }),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false }),
  ],
};
